django/metrics/urls.py
from django.views.generic.detail import DetailView
from django.views.generic import ListView

from django.conf.urls import patterns, url

from metrics.models import *
from metrics.views import *

urlpatterns = patterns('',
    url(r'^$',
        ListView.as_view(model=Metric),
        name='metric_list'),

    # Metric CRUD
    url(r'metric/create/?',
        MetricCreate.as_view(template_name='metric_list.html'),
        name='metric_create'),

    url(r'^metric/(?P<pk>\d+)/?$',
        MetricDetail.as_view(),
        name='metric_detail'),

    url(r'^metric/(?P<pk>\d+)/update/?$',
        MetricCreate.as_view(template_name='metric_list.html'),
        name='metric_update'),

    url(r'^metric/(?P<pk>\d+)/delete/?$',
        MetricDelete.as_view(template_name='metric_list.html'),
        name='metric_delete'),

    # Event CRUD
    url(r'^metric/(?P<metric_pk>\d+)/create/?$',
        EventCreate.as_view(),
        name='event_create'),

    url(r'^metric/(?P<metric_pk>\d+)/event_(?P<pk>\d+)/?$',
        DetailView.as_view(model=Event),
        name='event_detail'),
)

django/statsme/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'statsme.views.home', name='home'),
    # url(r'^statsme/', include('statsme.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^metrics/', include('metrics.urls')),
    url(r'^', include('metrics.urls')),
)

django/dashboards/models.py
from django.db import models

# Create your models here.

django/metrics/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Metric(models.Model):
    metric_type = models.CharField(max_length=200)
    identifier = models.CharField(max_length=200)

    def __unicode__(self):
        return 'Type: %s, Identifier: %s' % (
            self.metric_type, self.identifier)

    def get_absolute_url(self):
        return '/metrics' + reverse('metric_detail', kwargs={'pk': self.id}) + '/'


class Event(models.Model):
    metric = models.ForeignKey(Metric)
    occurred_at = models.DateTimeField()
    value = models.FloatField()

    def __unicode__(self):
        return 'Metric: %s, Occurred At: %s, Value: %s\n' % (
            self.metric.identifier, self.occurred_at, self.value)

    def get_absolute_url(self):
        return '/metrics/' + reverse('event_detail', kwargs={'metric_pk': self.metric.id, 'pk': self.id}) + '/'

django/polls/models.py
from django.db import models


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

django/dashboards/views.py
from django.shortcuts import render

# Create your views here.

django/metrics/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View

from django.core.urlresolvers import reverse_lazy
from django.utils import timezone

import logging

from models import *


class MetricListContextView(object):
    def get_context_data(self, **kwargs):
        context = super(MetricListContextView, self).get_context_data(**kwargs)
        context['metric_list'] = Metric.objects.all()
        return context


# Metric CRUD
class MetricCreate(CreateView):
    model = Metric
    fields = ['identifier']


class MetricDetail(MetricListContextView, DetailView):
    model = Metric

    def get_context_data(self, **kwargs):
        context = super(MetricDetail, self).get_context_data(**kwargs)
        context['metric_id'] = self.object.id
        return context


class MetricUpdate(UpdateView):
    model = Metric
    fields = ['identifier']


class MetricDelete(DeleteView):
    model = Metric
    success_url = reverse_lazy('metric-list')


# Event CRUD
class EventCreate(View):
    def post(self, *args, **kwargs):
        metric = get_object_or_404(Metric, pk=self.kwargs['metric_pk'])
        value = self.request.POST['value']
        event = Event(metric=metric, occurred_at=timezone.now(), value=value)
        event.save()
        redirect_url = event.metric.get_absolute_url()
        logging.info(redirect_url)
        return HttpResponseRedirect(redirect_url)


class EventDetail(View):
    pass


class EventUpdate(View):
    pass


class EventDelete(View):
    pass

django/polls/views.py
from django.shortcuts import render

# Create your views here.

django/metrics/templates/event_detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ object.metric.identifier }}</h1>
<p>
    Value {{ object.value }} recorded at {{ object.occurred_at }}.
</p>
{% endblock }

django/metrics/templates/metric_detail.html
{% extends "base.html" %}

{% block content %}
<hr />
<form class="form-search" action='create' method="post">
  <input type="number" class="input-medium search-query" name="value">
  <input type="submit" class="btn" value="Trigger Event" />
</form>

<h2>Events</h2>
<table class="table table-striped">
    <thead>
    <tr>
        <th>Time</th>
        <th>Value</th>
    </tr>
    </thead>
    <tbody>
{% for event in object.event_set.all %}
    <tr>
        <td>{{ event.occurred_at }}</td>
        <td>{{ event.value }}</td>
    </tr>      
{% endfor %}
    </tbody>
</table>

{% endblock %}

django/metrics/templates/metric_list.html
{% extends "base.html" %}

{% block content %}
<h1>Metrics</h1>

<form name="create_metric" action="metric/create" method="post">
    <input type="text" name="identifier" class="input-medium search-query"/>
    <input type="submit" value="New Metric" class="btn btn-success"/>
</form>

{% endblock %}

django/templates/base.html
<!doctype html>
<html lang="en">
  <!-- HEAD -->
  <head>
    <title></title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="/static/css/bootstrap.css"  type="text/css"/>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">    
  </head>

  <!-- BODY -->
  <body>
    <!-- BASE DIV -->
    <div class="container">
        <!-- TITLE -->
        <h1 class="visible-desktop"><a href="#">Statsme</a></h1>

        <!-- NAV BAR -->
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                <!-- NAV BAR ITEMS -->
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">Projects</a></li>
              </ul>
            </div>
          </div>
        </div>

        <!-- CONTENT ROW -->
        <div class="row">
            <!-- RECENT METRICS -->
             <div class="span4">
                 <ul class="nav nav-list">
                    <li class="nav-header">Recent Metrics</li>
                {% for metric in metric_list|slice:"5" %}
                    <li><a href="{{ metric.get_absolute_url }}">{{ metric.identifier }}</a></li>
                {% endfor %}
                </ul>
             </div>
             <!-- CONTENT -->
             <div class="span8">
                 {% block content %}{% endblock %}
             </div>
         </div>        
    </div>

    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>
  </body>
</html>